### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by m-weigand** [bjesus/pidif#2]
Hi there,

first of all thank you very much for sharing this project! Would it be possible to clarify the licence situation? I would very much like to adopt pidif for use on the Pine64 PineNote and a clear open license would simplify things.

Thanks and cheers

Maximilian

**Comment by bjesus** [comment]
hey! would MIT be okay?

**Comment by m-weigand** [comment]
MIT would be wonderful ;-) Thanks!
